### ISSUE TITLE
CLI tooling tracking issue

### ISSUE THREAD

**Issue by MolotovCherry** [MolotovCherry/virtual-display-rs#48]
Original merge from PR #47. References #43 

- [x] Easy to read error message if client doesn't connect - [comment](https://github.com/MolotovCherry/virtual-display-rs/pull/47/files#r1414515201)
Something like 
> Failed to connect to driver; please ensure driver is running and working. Driver must also not be in use by any other tools, e.g. gui apps
- [x] Make `RequestState` more global - [comment](https://github.com/MolotovCherry/virtual-display-rs/pull/47/files#r1414517109)
- [x] Use smallest available IDs - [comment](https://github.com/MolotovCherry/virtual-display-rs/pull/47/files#r1414532982)
- [x] For `add`/`add-mode`/`remove-mode`, allow specifying custom refresh rates per monitor mode. Making it clearer to type is also a bonus. - [comment](https://github.com/MolotovCherry/virtual-display-rs/pull/47/files#r1414539525)
- [x] Deprecate mode indexes and allow selection of monitors by unique WIDTH/HEIGHT. Potentially also allow deleting only refresh rate instead of entire mode. - [comment](https://github.com/MolotovCherry/virtual-display-rs/pull/47/files#r1414544039). UX TBD
- [x] Make client connection global / always store requested state so it can be accessible anywhere. - [comment](https://github.com/MolotovCherry/virtual-display-rs/pull/47/files#r1414558684)
- [x] With global state, other checks can be made smarter, such as displaying an error when user tries to remove a monitor ID that doesn't exist.

Cc @kylewlacy

**Comment by MolotovCherry** [comment]
For anyone who wants to try it today, please see this discussion:
https://github.com/MolotovCherry/virtual-display-rs/discussions/60

**Comment by MolotovCherry** [comment]
Finished in #97
